.TH MKDIR_CD 1 2020-04-30 "Shell Functions" "Shell Command's"
.SH NAME
mkdir_cd \- create and enter into a directory
.SH SYNOPSIS
.SY mkdir_cd
.RI [ directory ]
.SH DESCRIPTION
mkdir_cd shell command allows user to create and enter into directory at same time 
this make ease of access of directory create with entering on it. mkdir_cd is shell
function it's use advantage of mkdir -p [directory] and cd [directory] commands.
.SH EXAMPLES
.SH AUTHOR
Ajil Raju <ajilraju01@gmail.com> .
